quarkus.http.port=5000

quarkus.log.level=INFO
quarkus.log.category."com.martinatanasov".level=INFO

# Open API
quarkus.smallrye-openapi.enabled=true
quarkus.smallrye-openapi.path=/openapi
mp.openapi.extensions.smallrye.info.title=Swagger
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API documentation for CRUD application

# Flyway
quarkus.flyway.migrate-at-start=false
#quarkus.flyway.schemas=public
quarkus.flyway.locations=classpath:db/migration
#quarkus.flyway.locations=classpath:db/migration/{vendor}

# Datasource:
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/users
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Datasource: 'test' profile (Argument: -Dquarkus.profile=test)
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa

quarkus.hibernate-orm.schema-management.strategy=validate
#quarkus.hibernate-orm.sql-load-script=h2/import.sql

# Required for building native image via GraalVM (this is specific for password4j dependency)
quarkus.native.additional-build-args=--initialize-at-run-time=com.password4j.AlgorithmFinder

#smallrye.jwt.sign.key.location=privateKey.pem
#mp.jwt.verify.publickey.location=publicKey.pem